Add Neo4j starter kit
hypermodeinc/modus-recipes pull request #34
Opened 2024-12-23 18:20 UTC by johnymontana

2024-12-23 23:55 UTC, jairad26 commented on neo4j/neo4j-modus-starter-kit/assembly/index.ts
> +  RETURN m.imdbRating AS rating, m.title AS title, m.plot AS plot, m.imdbId AS id
lets return this as an object to clean up line 60-64

2024-12-23 23:55 UTC, jairad26 commented on neo4j/neo4j-modus-starter-kit/assembly/index.ts
> +  const indexResult = neo4j.executeQuery(hostName, indexQuery);
this variable indexResult isnt used anywhere or returned, we can remove it, or return it for better code clarity

2024-12-23 23:55 UTC, jairad26 commented on neo4j/neo4j-modus-starter-kit/assembly/index.ts
> +  const movieResults: MovieResult[] = JSON.parse<MovieResult[]>(
let's separate this into two lines, 
```
const recordResults = results.Records[0].get("movieResults")
const movieResults = JSON.parse<MovieResult[]>(recordResults)
```

2024-12-23 23:55 UTC, jairad26 commented on neo4j/neo4j-modus-starter-kit/assembly/index.ts
> +    result.Records[0].get("movieResults"),
we should also check that `result.Records has length > 0` before accessing [0]

2024-12-24 12:34 UTC, ryanfoxtyler requested changes

2024-12-24 12:34 UTC, ryanfoxtyler commented on neo4j/neo4j-modus-starter-kit/.prettierrc
the existence of this file overrides the prettier config we have running through Trunk; I also wouldn't expect us to force prettier on users, so should be safe to remove from the recipe

2024-12-24 13:32 UTC, johnymontana commented on neo4j/neo4j-modus-starter-kit/.prettierrc
This file was created by the [default template in the modus sdk](https://github.com/hypermodeinc/modus/blob/main/sdk/assemblyscript/templates/default/.prettierrc), so for consistency IMO we should either remove it there or include here and figure out a way to align with trunk in this repo?

2024-12-24 14:09 UTC, ryanfoxtyler commented on neo4j/neo4j-modus-starter-kit/.prettierrc
fair, we're not applying similar opinions on Go projects, so I would lean toward removing it and embracing that Modus apps are likely going to be deployed alongside other non-Modus components in the same repo

we've removed this from other recipes, so I'd opt for consistency in this repo while we work through the CLI changes

2025-01-08 17:40 UTC, johnymontana commented on neo4j/neo4j-modus-starter-kit/assembly/index.ts
> +    result.Records[0].get("movieResults"),
updated

2025-01-08 17:41 UTC, johnymontana commented on neo4j/neo4j-modus-starter-kit/assembly/index.ts
> +  const movieResults: MovieResult[] = JSON.parse<MovieResult[]>(
updated

2025-01-08 17:41 UTC, johnymontana commented on neo4j/neo4j-modus-starter-kit/assembly/index.ts
> +  const indexResult = neo4j.executeQuery(hostName, indexQuery);
removed

2025-01-08 17:43 UTC, johnymontana commented on neo4j/neo4j-modus-starter-kit/assembly/index.ts
> +  RETURN m.imdbRating AS rating, m.title AS title, m.plot AS plot, m.imdbId AS id
I wanted to leave this one as an example of this approach for accessing returned values, but I added comments explaining this explicit approach with a pointer to the findSimilarMovies function below for a more concise type marshalling approach.

2025-01-08 17:54 UTC, ryanfoxtyler approved these changes

2025-01-08 18:49 UTC, merged